# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cass_storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import msg_data_pb2 as msg__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12\x63\x61ss_storage.proto\x12\x15services.cass_storage\x1a\x0emsg_data.proto"k\n\x0e\x43\x61ssMsgRequest\x12\x30\n\x0cmessage_data\x18\x01 \x01(\x0b\x32\x1a.services.msg_data.MsgData\x12\x12\n\nmessage_id\x18\x02 \x01(\x03\x12\x13\n\x0b\x64\x65livery_id\x18\x03 \x01(\x03"J\n\x0c\x43\x61ssMsgReply\x12:\n\x04\x63ode\x18\x01 \x01(\x0e\x32,.services.cass_storage.CassMessageStatusCode"8\n\x10\x43\x61ssInboxRequest\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x17\n\x0flast_max_msg_id\x18\x02 \x01(\x03"\x80\x01\n\x0e\x43\x61ssInboxReply\x12:\n\x04\x63ode\x18\x01 \x01(\x0e\x32,.services.cass_storage.CassMessageStatusCode\x12\x32\n\x08messages\x18\x02 \x03(\x0b\x32 .services.msg_data.ServerMsgData")\n\x12\x43\x61ssSessionRequest\x12\x13\n\x0bsession_ids\x18\x01 \x03(\x03"i\n\x10\x43\x61ssSessionReply\x12\x12\n\nsession_id\x18\x01 \x01(\x03\x12\r\n\x05token\x18\x02 \x01(\x0c\x12\x32\n\x08messages\x18\x03 \x03(\x0b\x32 .services.msg_data.ServerMsgData*X\n\x15\x43\x61ssMessageStatusCode\x12\x14\n\x10\x43\x41SS_MSG_SUCCESS\x10\x00\x12\x14\n\x10\x43\x41SS_MSG_TIMEOUT\x10\x01\x12\x13\n\x0f\x43\x41SS_MSG_FAILED\x10\x02\x32\x91\x03\n\x0b\x43\x61ssStorage\x12^\n\x0eWriteToSession\x12%.services.cass_storage.CassMsgRequest\x1a#.services.cass_storage.CassMsgReply"\x00\x12\\\n\x0cWriteToInbox\x12%.services.cass_storage.CassMsgRequest\x1a#.services.cass_storage.CassMsgReply"\x00\x12]\n\tReadInbox\x12\'.services.cass_storage.CassInboxRequest\x1a%.services.cass_storage.CassInboxReply"\x00\x12\x65\n\x0bReadSession\x12).services.cass_storage.CassSessionRequest\x1a\'.services.cass_storage.CassSessionReply"\x00\x30\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "cass_storage_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_CASSMESSAGESTATUSCODE"]._serialized_start = 585
    _globals["_CASSMESSAGESTATUSCODE"]._serialized_end = 673
    _globals["_CASSMSGREQUEST"]._serialized_start = 61
    _globals["_CASSMSGREQUEST"]._serialized_end = 168
    _globals["_CASSMSGREPLY"]._serialized_start = 170
    _globals["_CASSMSGREPLY"]._serialized_end = 244
    _globals["_CASSINBOXREQUEST"]._serialized_start = 246
    _globals["_CASSINBOXREQUEST"]._serialized_end = 302
    _globals["_CASSINBOXREPLY"]._serialized_start = 305
    _globals["_CASSINBOXREPLY"]._serialized_end = 433
    _globals["_CASSSESSIONREQUEST"]._serialized_start = 435
    _globals["_CASSSESSIONREQUEST"]._serialized_end = 476
    _globals["_CASSSESSIONREPLY"]._serialized_start = 478
    _globals["_CASSSESSIONREPLY"]._serialized_end = 583
    _globals["_CASSSTORAGE"]._serialized_start = 676
    _globals["_CASSSTORAGE"]._serialized_end = 1077
# @@protoc_insertion_point(module_scope)
