# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import downstream_pb2 as downstream__pb2


class DownstreamTransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeliverReadEvent = channel.unary_unary(
            "/services.downstream.DownstreamTransfer/DeliverReadEvent",
            request_serializer=downstream__pb2.ReadModelEvent.SerializeToString,
            response_deserializer=downstream__pb2.DeliverReadEventReply.FromString,
        )
        self.PullInboxMsg = channel.unary_unary(
            "/services.downstream.DownstreamTransfer/PullInboxMsg",
            request_serializer=downstream__pb2.PullInboxRequest.SerializeToString,
            response_deserializer=downstream__pb2.PullInboxReply.FromString,
        )


class DownstreamTransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeliverReadEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PullInboxMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DownstreamTransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "DeliverReadEvent": grpc.unary_unary_rpc_method_handler(
            servicer.DeliverReadEvent,
            request_deserializer=downstream__pb2.ReadModelEvent.FromString,
            response_serializer=downstream__pb2.DeliverReadEventReply.SerializeToString,
        ),
        "PullInboxMsg": grpc.unary_unary_rpc_method_handler(
            servicer.PullInboxMsg,
            request_deserializer=downstream__pb2.PullInboxRequest.FromString,
            response_serializer=downstream__pb2.PullInboxReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "services.downstream.DownstreamTransfer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DownstreamTransfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeliverReadEvent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/services.downstream.DownstreamTransfer/DeliverReadEvent",
            downstream__pb2.ReadModelEvent.SerializeToString,
            downstream__pb2.DeliverReadEventReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def PullInboxMsg(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/services.downstream.DownstreamTransfer/PullInboxMsg",
            downstream__pb2.PullInboxRequest.SerializeToString,
            downstream__pb2.PullInboxReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
