# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: downstream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import msg_data_pb2 as msg__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x64ownstream.proto\x12\x13services.downstream\x1a\x0emsg_data.proto"\x93\x01\n\x0eReadModelEvent\x12\x39\n\x08\x65vent_tp\x18\x01 \x01(\x0e\x32\'.services.downstream.ReadModelEventType\x12\x13\n\x0b\x64\x65livery_id\x18\x02 \x01(\x03\x12\x31\n\x07message\x18\x03 \x01(\x0b\x32 .services.msg_data.ServerMsgData"T\n\x15\x44\x65liverReadEventReply\x12;\n\x06status\x18\x01 \x01(\x0e\x32+.services.downstream.DeliverReadEventStatus"<\n\x10PullInboxRequest\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x1b\n\x13received_max_msg_id\x18\x02 \x01(\x03"\x81\x01\n\x0ePullInboxReply\x12;\n\x06status\x18\x01 \x01(\x0e\x32+.services.downstream.DeliverReadEventStatus\x12\x32\n\x08messages\x18\x02 \x03(\x0b\x32 .services.msg_data.ServerMsgData*K\n\x12ReadModelEventType\x12\x1a\n\x16READ_MODEL_SINGLE_CHAT\x10\x00\x12\x19\n\x15READ_MODEL_GROUP_CHAT\x10\x01*_\n\x16\x44\x65liverReadEventStatus\x12\x16\n\x12READ_MODEL_SUCCESS\x10\x00\x12\x16\n\x12READ_MODEL_TIMEOUT\x10\x01\x12\x15\n\x11READ_MODEL_FAILED\x10\x02\x32\xd9\x01\n\x12\x44ownstreamTransfer\x12\x65\n\x10\x44\x65liverReadEvent\x12#.services.downstream.ReadModelEvent\x1a*.services.downstream.DeliverReadEventReply"\x00\x12\\\n\x0cPullInboxMsg\x12%.services.downstream.PullInboxRequest\x1a#.services.downstream.PullInboxReply"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "downstream_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_READMODELEVENTTYPE"]._serialized_start = 487
    _globals["_READMODELEVENTTYPE"]._serialized_end = 562
    _globals["_DELIVERREADEVENTSTATUS"]._serialized_start = 564
    _globals["_DELIVERREADEVENTSTATUS"]._serialized_end = 659
    _globals["_READMODELEVENT"]._serialized_start = 58
    _globals["_READMODELEVENT"]._serialized_end = 205
    _globals["_DELIVERREADEVENTREPLY"]._serialized_start = 207
    _globals["_DELIVERREADEVENTREPLY"]._serialized_end = 291
    _globals["_PULLINBOXREQUEST"]._serialized_start = 293
    _globals["_PULLINBOXREQUEST"]._serialized_end = 353
    _globals["_PULLINBOXREPLY"]._serialized_start = 356
    _globals["_PULLINBOXREPLY"]._serialized_end = 485
    _globals["_DOWNSTREAMTRANSFER"]._serialized_start = 662
    _globals["_DOWNSTREAMTRANSFER"]._serialized_end = 879
# @@protoc_insertion_point(module_scope)
