# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0emsg_data.proto\x12\x11services.msg_data"S\n\x07MsgData\x12\x12\n\nsession_id\x18\x01 \x01(\x03\x12\x11\n\tsender_id\x18\x02 \x01(\r\x12\x13\n\x0breceiver_id\x18\x03 \x01(\r\x12\x0c\n\x04text\x18\x04 \x01(\t"N\n\rClientMsgData\x12(\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1a.services.msg_data.MsgData\x12\x13\n\x0b\x64\x65livery_id\x18\x02 \x01(\x03"M\n\rServerMsgData\x12(\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1a.services.msg_data.MsgData\x12\x12\n\nmessage_id\x18\x02 \x01(\x03"c\n\x0eRStreamMsgData\x12(\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1a.services.msg_data.MsgData\x12\x13\n\x0b\x64\x65livery_id\x18\x02 \x01(\x03\x12\x12\n\nmessage_id\x18\x03 \x01(\x03"n\n\nDLQMsgData\x12/\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1f.services.msg_data.DLQMsgAction\x12/\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32!.services.msg_data.RStreamMsgData*E\n\x0c\x44LQMsgAction\x12\x0b\n\x07\x44LQ_ALL\x10\x00\x12\x14\n\x10\x44LQ_SESSION_ONLY\x10\x01\x12\x12\n\x0e\x44LQ_INBOX_ONLY\x10\x02\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "msg_data_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_DLQMSGACTION"]._serialized_start = 494
    _globals["_DLQMSGACTION"]._serialized_end = 563
    _globals["_MSGDATA"]._serialized_start = 37
    _globals["_MSGDATA"]._serialized_end = 120
    _globals["_CLIENTMSGDATA"]._serialized_start = 122
    _globals["_CLIENTMSGDATA"]._serialized_end = 200
    _globals["_SERVERMSGDATA"]._serialized_start = 202
    _globals["_SERVERMSGDATA"]._serialized_end = 279
    _globals["_RSTREAMMSGDATA"]._serialized_start = 281
    _globals["_RSTREAMMSGDATA"]._serialized_end = 380
    _globals["_DLQMSGDATA"]._serialized_start = 382
    _globals["_DLQMSGDATA"]._serialized_end = 492
# @@protoc_insertion_point(module_scope)
