# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upstream.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import msg_data_pb2 as msg__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eupstream.proto\x12\x11services.upstream\x1a\x0emsg_data.proto"M\n\x13\x44\x65liverUpMsgRequest\x12\x36\n\x0cmessage_data\x18\x01 \x01(\x0b\x32 .services.msg_data.ClientMsgData"x\n\x11\x44\x65liverUpMsgReply\x12;\n\x04\x63ode\x18\x01 \x01(\x0e\x32-.services.upstream.UpstreamTransferStatusCode\x12\x17\n\nmessage_id\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\r\n\x0b_message_id*x\n\x1aUpstreamTransferStatusCode\x12\x1d\n\x19UPSTREAM_DELIVERY_SUCCESS\x10\x00\x12\x1d\n\x19UPSTREAM_DELIVERY_TIMEOUT\x10\x01\x12\x1c\n\x18UPSTREAM_DELIVERY_FAILED\x10\x02\x32t\n\x10UpstreamTransfer\x12`\n\x0e\x44\x65liverMessage\x12&.services.upstream.DeliverUpMsgRequest\x1a$.services.upstream.DeliverUpMsgReply"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "upstream_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_UPSTREAMTRANSFERSTATUSCODE"]._serialized_start = 254
    _globals["_UPSTREAMTRANSFERSTATUSCODE"]._serialized_end = 374
    _globals["_DELIVERUPMSGREQUEST"]._serialized_start = 53
    _globals["_DELIVERUPMSGREQUEST"]._serialized_end = 130
    _globals["_DELIVERUPMSGREPLY"]._serialized_start = 132
    _globals["_DELIVERUPMSGREPLY"]._serialized_end = 252
    _globals["_UPSTREAMTRANSFER"]._serialized_start = 376
    _globals["_UPSTREAMTRANSFER"]._serialized_end = 492
# @@protoc_insertion_point(module_scope)
