# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import snowflake_pb2 as snowflake__pb2


class SnowflakeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.flickClock = channel.unary_unary(
            "/services.snowflake.Snowflake/flickClock",
            request_serializer=snowflake__pb2.SnowflakeRequest.SerializeToString,
            response_deserializer=snowflake__pb2.SnowflakeReply.FromString,
        )


class SnowflakeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def flickClock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SnowflakeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "flickClock": grpc.unary_unary_rpc_method_handler(
            servicer.flickClock,
            request_deserializer=snowflake__pb2.SnowflakeRequest.FromString,
            response_serializer=snowflake__pb2.SnowflakeReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "services.snowflake.Snowflake", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Snowflake(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def flickClock(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/services.snowflake.Snowflake/flickClock",
            snowflake__pb2.SnowflakeRequest.SerializeToString,
            snowflake__pb2.SnowflakeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
