# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x12\x05\x63hatp\"\x93\x01\n\x0bUserSession\x12\x0c\n\x04wsid\x18\x01 \x01(\t\x12&\n\x0b\x64\x65vice_type\x18\x02 \x03(\x0e\x32\x11.chatp.DeviceType\x12\x18\n\x10last_online_time\x18\x03 \x01(\x03\x12\x1e\n\x11last_offline_time\x18\x04 \x01(\x03H\x00\x88\x01\x01\x42\x14\n\x12_last_offline_time*A\n\nDeviceType\x12\x0c\n\x08Terminal\x10\x00\x12\x06\n\x02PC\x10\x01\x12\x07\n\x03Web\x10\x02\x12\x0b\n\x07\x41ndriod\x10\x03\x12\x07\n\x03IOS\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_DEVICETYPE']._serialized_start=174
  _globals['_DEVICETYPE']._serialized_end=239
  _globals['_USERSESSION']._serialized_start=25
  _globals['_USERSESSION']._serialized_end=172
# @@protoc_insertion_point(module_scope)
