# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstatistic.proto\x12\x05\x63hatp\"1\n\x08LoadItem\x12\x10\n\x08srv_addr\x18\x01 \x01(\t\x12\x13\n\x0busage_count\x18\x02 \x01(\x05\"c\n\x08LoadInfo\x12\x10\n\x08proc_seq\x18\x01 \x01(\x05\x12\x10\n\x08srv_name\x18\x02 \x01(\t\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05\x12\x1e\n\x05loads\x18\x04 \x03(\x0b\x32\x0f.chatp.LoadItemb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistic_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_LOADITEM']._serialized_start=26
  _globals['_LOADITEM']._serialized_end=75
  _globals['_LOADINFO']._serialized_start=77
  _globals['_LOADINFO']._serialized_end=176
# @@protoc_insertion_point(module_scope)
