# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import friend_pb2 as friend__pb2


class FriendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFriendList = channel.unary_unary(
            "/services.friend.Friend/GetFriendList",
            request_serializer=friend__pb2.FriendListRequest.SerializeToString,
            response_deserializer=friend__pb2.FriendListReply.FromString,
        )
        self.AddFriend = channel.unary_unary(
            "/services.friend.Friend/AddFriend",
            request_serializer=friend__pb2.FriendRequest.SerializeToString,
            response_deserializer=friend__pb2.FriendRequestReply.FromString,
        )
        self.AddFriendBatch = channel.unary_unary(
            "/services.friend.Friend/AddFriendBatch",
            request_serializer=friend__pb2.FriendRequestBatch.SerializeToString,
            response_deserializer=friend__pb2.FriendRequestReply.FromString,
        )
        self.ConfirmFriend = channel.unary_unary(
            "/services.friend.Friend/ConfirmFriend",
            request_serializer=friend__pb2.FriendConfirm.SerializeToString,
            response_deserializer=friend__pb2.FriendConfirmReply.FromString,
        )


class FriendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFriendList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddFriend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddFriendBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ConfirmFriend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FriendServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetFriendList": grpc.unary_unary_rpc_method_handler(
            servicer.GetFriendList,
            request_deserializer=friend__pb2.FriendListRequest.FromString,
            response_serializer=friend__pb2.FriendListReply.SerializeToString,
        ),
        "AddFriend": grpc.unary_unary_rpc_method_handler(
            servicer.AddFriend,
            request_deserializer=friend__pb2.FriendRequest.FromString,
            response_serializer=friend__pb2.FriendRequestReply.SerializeToString,
        ),
        "AddFriendBatch": grpc.unary_unary_rpc_method_handler(
            servicer.AddFriendBatch,
            request_deserializer=friend__pb2.FriendRequestBatch.FromString,
            response_serializer=friend__pb2.FriendRequestReply.SerializeToString,
        ),
        "ConfirmFriend": grpc.unary_unary_rpc_method_handler(
            servicer.ConfirmFriend,
            request_deserializer=friend__pb2.FriendConfirm.FromString,
            response_serializer=friend__pb2.FriendConfirmReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "services.friend.Friend", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Friend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFriendList(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/services.friend.Friend/GetFriendList",
            friend__pb2.FriendListRequest.SerializeToString,
            friend__pb2.FriendListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AddFriend(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/services.friend.Friend/AddFriend",
            friend__pb2.FriendRequest.SerializeToString,
            friend__pb2.FriendRequestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def AddFriendBatch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/services.friend.Friend/AddFriendBatch",
            friend__pb2.FriendRequestBatch.SerializeToString,
            friend__pb2.FriendRequestReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def ConfirmFriend(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/services.friend.Friend/ConfirmFriend",
            friend__pb2.FriendConfirm.SerializeToString,
            friend__pb2.FriendConfirmReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
