from enum import IntEnum


class WsLoginCode(IntEnum):
    CONNECTED = 0
    LOGIN_TIMEOUT = 1

    # step 1: websocket handshake
    REJECTED = 2
    REFRESH_REQUIRED = 3

    # step 2: logical negotiate
    LOGIN_CONFLICT = 4
    NEGOTIATE_TIMEOUT = 5
    RETRY_LATER = 6
    INTERNAL_ERROR = 7
    SERVER_DOWN = 8
    UNKNOW_ERROR = 9


class WsAppEvent(IntEnum):
    READY = 0
    ACTIVE = 1
    CLOSING = 2
    CLOSED = 3
    KICKED_OFF = 5
    NETWORK_ERROR = 6
    INBOUND_FRIEND_REQUEST = 7
    INBOUND_FRIEND_CONFIRM = 8
    OUTBOUND_FRIEND_REQUEST = 9
    INBOUND_MESSAGE = 10
    OUTBOUND_MESSAGE_TIMEOUT = 11
    INBOUND_ACKED_MESSAGE = 12


CONNECTED = WsLoginCode.CONNECTED
LOGIN_TIMEOUT = WsLoginCode.LOGIN_TIMEOUT
REJECTED = WsLoginCode.REJECTED
REFRESH_REQUIRED = WsLoginCode.REFRESH_REQUIRED
LOGIN_CONFLICT = WsLoginCode.LOGIN_CONFLICT
NEGOTIATE_TIMEOUT = WsLoginCode.NEGOTIATE_TIMEOUT
RETRY_LATER = WsLoginCode.RETRY_LATER
INTERNAL_ERROR = WsLoginCode.INTERNAL_ERROR
SERVER_DOWN = WsLoginCode.SERVER_DOWN
UNKNOW_ERROR = WsLoginCode.UNKNOW_ERROR

READY = WsAppEvent.READY
ACTIVE = WsAppEvent.ACTIVE
CLOSING = WsAppEvent.CLOSING
CLOSED = WsAppEvent.CLOSED
KICKED_OFF = WsAppEvent.KICKED_OFF
NETWORK_ERROR = WsAppEvent.NETWORK_ERROR
INBOUND_FRIEND_REQUEST = WsAppEvent.INBOUND_FRIEND_REQUEST
INBOUND_FRIEND_CONFIRM = WsAppEvent.INBOUND_FRIEND_CONFIRM
OUTBOUND_FRIEND_REQUEST = WsAppEvent.OUTBOUND_FRIEND_REQUEST
INBOUND_MESSAGE = WsAppEvent.INBOUND_MESSAGE
INBOUND_ACKED_MESSAGE = WsAppEvent.INBOUND_ACKED_MESSAGE
OUTBOUND_MESSAGE_TIMEOUT = WsAppEvent.OUTBOUND_MESSAGE_TIMEOUT

WS_1000_NORMAL_CLOSURE = 1000
WS_1001_GOING_AWAY = 1001
WS_1002_PROTOCOL_ERROR = 1002
WS_1003_UNSUPPORTED_DATA = 1003
WS_1005_NO_STATUS_RCVD = 1005
WS_1006_ABNORMAL_CLOSURE = 1006
WS_1007_INVALID_FRAME_PAYLOAD_DATA = 1007
WS_1008_POLICY_VIOLATION = 1008
WS_1009_MESSAGE_TOO_BIG = 1009
WS_1010_MANDATORY_EXT = 1010
WS_1011_INTERNAL_ERROR = 1011
WS_1012_SERVICE_RESTART = 1012
WS_1013_TRY_AGAIN_LATER = 1013
WS_1014_BAD_GATEWAY = 1014
WS_1015_TLS_HANDSHAKE = 1015

WS_4001_REFRESH_REQUIRED = 4001
WS_4003_NEGOTIATE_TIMEOUT = 4003
WS_4004_SERVER_SHUTDOWN = 4004
WS_4005_SEND_TOO_FAST = 4005
WS_4007_KICKED_OFF = 4007
WS_4008_CONNECT_CONFLICT = 4008
